name: servus_iap_backend
description: IAP Backend
version: 0.0.1
homepage: https://www.servusflutter.com
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  postgres: ^3.5.6

  # grpc
  grpc: ^4.0.4
  protobuf: ^4.0.0

dev_dependencies:
  lints: 5.1.1
  build_runner: ^2.4.15
