name: servus_iap_flutter
description: "Servus iap flutter package"
version: 0.0.1
homepage: https://www.servusflutter.com

environment:
  sdk: ^3.7.2
  flutter: ^3.29.0

dependencies:
  flutter:
    sdk: flutter
  grpc: ^4.0.4
  protobuf: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
